name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hello there!"
            echo "How've you been doing?"
      - name: Print goodbye
        run: echo "Done - see ya!"
